include:
  - project: tq-em/build/docker/toolchain-ci
    file: apps.yml
    ref: v7.0.0_tc6.1.0

Lint:
  extends: .go-lint

Code Generation:
  extends: .go-generate-code

Unit tests:
  extends: .go-unit-tests

Go Sec Linter:
  extends: .go-sec

Gitleaks:
  extends: .gitleaks
