image: ${CI_REGISTRY}/tq-em/build/toolchain/amd64:latest

Lint:
  script:
    - golint -set_exit_status $(go list ./...)
  tags:
    - tq-em-linux

Code Generation:
  before_script:
    - yarn install
  script:
    - go generate -v ./...
    - yarn generate
    - git add :/
    - git diff --exit-code HEAD
  tags:
    - tq-em-linux
