include:
- project: tq-em/common/ci
  file: apps.yml
  ref: v4.2.0_tc3.16.1

Lint:
  extends: .go-lint

Code Generation:
  extends: .go-generate-code

Unit tests:
  extends: .go-unit-tests

Go Sec Linter:
  extends: .go-sec

Gitleaks:
  extends: .gitleaks
