include:
  - project: tq-em/build/docker/toolchain-ci
    file: apps.yml
    ref: v5.1.2_tc5.0.6

Lint:
  extends: .go-lint

Code Generation:
  extends: .go-generate-code

Unit tests:
  extends: .go-unit-tests

Go Sec Linter:
  extends: .go-sec

Gitleaks:
  extends: .gitleaks
