// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gdr.proto

package gdr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// devicetype - declares which Type of Device the Data Source is
//    		  - necessary for Sankey-Diagram
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNKNOWN             DeviceType = 0
	DeviceType_DEVICE_TYPE_PHOTOVOLTAIC_SYSTEM DeviceType = 1
	DeviceType_DEVICE_TYPE_ELECTRIC_VEHICLE    DeviceType = 2
	DeviceType_DEVICE_TYPE_BATTERY             DeviceType = 3
)

var DeviceType_name = map[int32]string{
	0: "DEVICE_TYPE_UNKNOWN",
	1: "DEVICE_TYPE_PHOTOVOLTAIC_SYSTEM",
	2: "DEVICE_TYPE_ELECTRIC_VEHICLE",
	3: "DEVICE_TYPE_BATTERY",
}

var DeviceType_value = map[string]int32{
	"DEVICE_TYPE_UNKNOWN":             0,
	"DEVICE_TYPE_PHOTOVOLTAIC_SYSTEM": 1,
	"DEVICE_TYPE_ELECTRIC_VEHICLE":    2,
	"DEVICE_TYPE_BATTERY":             3,
}

func (x DeviceType) String() string {
	return proto.EnumName(DeviceType_name, int32(x))
}

func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{0}
}

// Status OK = Datasource updated Data, GDR Updated
// Status WARNING = Datasource updated Data but configuration is needed
// Status Error = Datasource did not updated Data (Maybe broken)
type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_STATUS_OK      Status = 1
	Status_STATUS_WARNING Status = 2
	Status_STATUS_ERROR   Status = 3
)

var Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_OK",
	2: "STATUS_WARNING",
	3: "STATUS_ERROR",
}

var Status_value = map[string]int32{
	"STATUS_UNKNOWN": 0,
	"STATUS_OK":      1,
	"STATUS_WARNING": 2,
	"STATUS_ERROR":   3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{1}
}

// Class Consumer = Consumes Energy, Power, ...
// Class Producer = Produces Energy, Power, ...
// Class Hybrid = Consumes or Produces Energy, Power, ...
type Class int32

const (
	Class_CLASS_UNKNOWN  Class = 0
	Class_CLASS_CONSUMER Class = 1
	Class_CLASS_PRODUCER Class = 2
	Class_CLASS_HYBRID   Class = 3
)

var Class_name = map[int32]string{
	0: "CLASS_UNKNOWN",
	1: "CLASS_CONSUMER",
	2: "CLASS_PRODUCER",
	3: "CLASS_HYBRID",
}

var Class_value = map[string]int32{
	"CLASS_UNKNOWN":  0,
	"CLASS_CONSUMER": 1,
	"CLASS_PRODUCER": 2,
	"CLASS_HYBRID":   3,
}

func (x Class) String() string {
	return proto.EnumName(Class_name, int32(x))
}

func (Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{2}
}

// GDRs is the message type wich is published to the mqtt Handler for GDR
type GDRs struct {
	GDRs                 map[string]*GDR `protobuf:"bytes,1,rep,name=GDRs,json=gDRs,proto3" json:"GDRs" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GDRs) Reset()         { *m = GDRs{} }
func (m *GDRs) String() string { return proto.CompactTextString(m) }
func (*GDRs) ProtoMessage()    {}
func (*GDRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{0}
}

func (m *GDRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GDRs.Unmarshal(m, b)
}
func (m *GDRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GDRs.Marshal(b, m, deterministic)
}
func (m *GDRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GDRs.Merge(m, src)
}
func (m *GDRs) XXX_Size() int {
	return xxx_messageInfo_GDRs.Size(m)
}
func (m *GDRs) XXX_DiscardUnknown() {
	xxx_messageInfo_GDRs.DiscardUnknown(m)
}

var xxx_messageInfo_GDRs proto.InternalMessageInfo

func (m *GDRs) GetGDRs() map[string]*GDR {
	if m != nil {
		return m.GDRs
	}
	return nil
}

// GCRs is the message type wich is published to the mqtt Handler for GCR
type GCRs struct {
	GCRs                 map[string]*GCR `protobuf:"bytes,1,rep,name=GCRs,json=gCRs,proto3" json:"GCRs" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GCRs) Reset()         { *m = GCRs{} }
func (m *GCRs) String() string { return proto.CompactTextString(m) }
func (*GCRs) ProtoMessage()    {}
func (*GCRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{1}
}

func (m *GCRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCRs.Unmarshal(m, b)
}
func (m *GCRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCRs.Marshal(b, m, deterministic)
}
func (m *GCRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCRs.Merge(m, src)
}
func (m *GCRs) XXX_Size() int {
	return xxx_messageInfo_GCRs.Size(m)
}
func (m *GCRs) XXX_DiscardUnknown() {
	xxx_messageInfo_GCRs.DiscardUnknown(m)
}

var xxx_messageInfo_GCRs proto.InternalMessageInfo

func (m *GCRs) GetGCRs() map[string]*GCR {
	if m != nil {
		return m.GCRs
	}
	return nil
}

// GDR = Generic Data Record
// id - unique identification (Same to associated GCR)
// status - see Status declaration
// timestamp - last time Data was updated
// values - Key = Binary ObisCode, Value = Value of ObisCode
//        - based on ObisCode the basic Data information
//        - in groups here is the comparison of the childs data information
type GDR struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Status               Status               `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp"`
	Values               map[uint64]uint64    `protobuf:"bytes,4,rep,name=values,proto3" json:"values" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GDR) Reset()         { *m = GDR{} }
func (m *GDR) String() string { return proto.CompactTextString(m) }
func (*GDR) ProtoMessage()    {}
func (*GDR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{2}
}

func (m *GDR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GDR.Unmarshal(m, b)
}
func (m *GDR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GDR.Marshal(b, m, deterministic)
}
func (m *GDR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GDR.Merge(m, src)
}
func (m *GDR) XXX_Size() int {
	return xxx_messageInfo_GDR.Size(m)
}
func (m *GDR) XXX_DiscardUnknown() {
	xxx_messageInfo_GDR.DiscardUnknown(m)
}

var xxx_messageInfo_GDR proto.InternalMessageInfo

func (m *GDR) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GDR) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNKNOWN
}

func (m *GDR) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GDR) GetValues() map[uint64]uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

// GCR = Generic Config Record
// id - unique identification (Same to associated GDR)
// label - describes the Datasource
// class - see Class declaration
// sources - points to the childs of the measuring point
// 	       - references on the GDR ids
//         - structure of groupings
// codes  - based on Binary ObisCodes
//        - declares which ObisCodes the associated GDR has
// devicetype - see DeviceType declaration
type GCR struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Label                string     `protobuf:"bytes,2,opt,name=label,proto3" json:"label"`
	Class                Class      `protobuf:"varint,3,opt,name=class,proto3,enum=Class" json:"class"`
	Sources              []string   `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources"`
	Codes                []uint64   `protobuf:"varint,5,rep,packed,name=codes,proto3" json:"codes"`
	Devicetype           DeviceType `protobuf:"varint,6,opt,name=devicetype,proto3,enum=DeviceType" json:"devicetype"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GCR) Reset()         { *m = GCR{} }
func (m *GCR) String() string { return proto.CompactTextString(m) }
func (*GCR) ProtoMessage()    {}
func (*GCR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88fa3b9b3f72b96, []int{3}
}

func (m *GCR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCR.Unmarshal(m, b)
}
func (m *GCR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCR.Marshal(b, m, deterministic)
}
func (m *GCR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCR.Merge(m, src)
}
func (m *GCR) XXX_Size() int {
	return xxx_messageInfo_GCR.Size(m)
}
func (m *GCR) XXX_DiscardUnknown() {
	xxx_messageInfo_GCR.DiscardUnknown(m)
}

var xxx_messageInfo_GCR proto.InternalMessageInfo

func (m *GCR) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GCR) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *GCR) GetClass() Class {
	if m != nil {
		return m.Class
	}
	return Class_CLASS_UNKNOWN
}

func (m *GCR) GetSources() []string {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *GCR) GetCodes() []uint64 {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *GCR) GetDevicetype() DeviceType {
	if m != nil {
		return m.Devicetype
	}
	return DeviceType_DEVICE_TYPE_UNKNOWN
}

func init() {
	proto.RegisterEnum("DeviceType", DeviceType_name, DeviceType_value)
	proto.RegisterEnum("Status", Status_name, Status_value)
	proto.RegisterEnum("Class", Class_name, Class_value)
	proto.RegisterType((*GDRs)(nil), "GDRs")
	proto.RegisterMapType((map[string]*GDR)(nil), "GDRs.GDRsEntry")
	proto.RegisterType((*GCRs)(nil), "GCRs")
	proto.RegisterMapType((map[string]*GCR)(nil), "GCRs.GCRsEntry")
	proto.RegisterType((*GDR)(nil), "GDR")
	proto.RegisterMapType((map[uint64]uint64)(nil), "GDR.ValuesEntry")
	proto.RegisterType((*GCR)(nil), "GCR")
}

func init() { proto.RegisterFile("gdr.proto", fileDescriptor_f88fa3b9b3f72b96) }

var fileDescriptor_f88fa3b9b3f72b96 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6e, 0xda, 0x4c,
	0x14, 0xfd, 0xfc, 0x83, 0x23, 0x5f, 0xbe, 0x50, 0x77, 0x1a, 0xa9, 0x16, 0x8a, 0x04, 0x6a, 0x36,
	0x88, 0x4a, 0x8e, 0x44, 0x37, 0x69, 0xa5, 0x2e, 0xc8, 0x78, 0x04, 0x56, 0x88, 0x4d, 0xaf, 0x07,
	0x22, 0x56, 0x88, 0x1f, 0x17, 0xd1, 0x92, 0x1a, 0x61, 0x13, 0x89, 0x07, 0xe8, 0xab, 0xf4, 0x8d,
	0xfa, 0x3e, 0x95, 0x67, 0x4c, 0x98, 0xb6, 0xab, 0x6e, 0x6c, 0x9f, 0x73, 0xef, 0x3d, 0xc7, 0xe7,
	0xce, 0x80, 0xbd, 0x5a, 0xee, 0xbc, 0xed, 0x2e, 0xcd, 0xd3, 0x7a, 0x63, 0x95, 0xa6, 0xab, 0x4d,
	0x72, 0x2d, 0xd0, 0x7c, 0xff, 0xf9, 0x3a, 0x5f, 0x3f, 0x26, 0x59, 0x3e, 0x7b, 0xdc, 0xca, 0x86,
	0x37, 0x5f, 0xc0, 0xec, 0xf9, 0x98, 0x91, 0x2b, 0xf9, 0x76, 0xb5, 0xa6, 0xd1, 0xaa, 0x76, 0x5e,
	0x78, 0x05, 0x10, 0x0f, 0xf6, 0x2d, 0xdf, 0x1d, 0xd0, 0x5c, 0xf9, 0x98, 0xd5, 0x3f, 0x82, 0xfd,
	0x4c, 0x11, 0x07, 0x8c, 0xaf, 0xc9, 0xc1, 0xd5, 0x9a, 0x5a, 0xcb, 0xc6, 0xe2, 0x93, 0xd4, 0xa1,
	0xf2, 0x34, 0xdb, 0xec, 0x13, 0x57, 0x6f, 0x6a, 0xad, 0x6a, 0xc7, 0x2c, 0xe6, 0x51, 0x52, 0x1f,
	0xf4, 0x1b, 0x4d, 0x78, 0xd1, 0xd2, 0x8b, 0xaa, 0x5e, 0xb4, 0xf0, 0xa2, 0x27, 0x2f, 0x5a, 0x7a,
	0xd1, 0x7f, 0xf1, 0xa2, 0xbf, 0x79, 0xfd, 0xd4, 0xc0, 0xe8, 0xf9, 0x48, 0x6a, 0xa0, 0xaf, 0x97,
	0xe5, 0xa0, 0xbe, 0x5e, 0x92, 0x06, 0x58, 0x59, 0x3e, 0xcb, 0xf7, 0x99, 0x18, 0xac, 0x75, 0xce,
	0xbc, 0x58, 0x40, 0x2c, 0x69, 0x72, 0x03, 0xf6, 0xf3, 0x8e, 0x5c, 0x43, 0x88, 0xd7, 0x3d, 0xb9,
	0x45, 0xef, 0xb8, 0x45, 0x8f, 0x1f, 0x3b, 0xf0, 0xd4, 0x4c, 0x5a, 0x60, 0x09, 0xff, 0xcc, 0x35,
	0x45, 0x30, 0xa7, 0xc8, 0xef, 0x8d, 0x05, 0x25, 0x93, 0x95, 0xf5, 0xfa, 0x7b, 0xa8, 0x2a, 0xb4,
	0x9a, 0xce, 0x94, 0xe9, 0x2e, 0xd4, 0x74, 0xa6, 0x9a, 0xeb, 0x47, 0x91, 0x8b, 0xfe, 0x9d, 0xeb,
	0x02, 0x2a, 0x9b, 0xd9, 0x3c, 0xd9, 0x88, 0x09, 0x1b, 0x25, 0x20, 0x97, 0x50, 0x59, 0x6c, 0x66,
	0x59, 0x26, 0x82, 0xd4, 0x3a, 0x96, 0x47, 0x0b, 0x84, 0x92, 0x24, 0x2e, 0x9c, 0x65, 0xe9, 0x7e,
	0xb7, 0x28, 0xff, 0xd8, 0xc6, 0x23, 0x2c, 0xd4, 0x16, 0xe9, 0x32, 0xc9, 0xdc, 0x4a, 0xd3, 0x28,
	0xfc, 0x05, 0x20, 0x6f, 0x01, 0x96, 0xc9, 0xd3, 0x7a, 0x91, 0xe4, 0x87, 0x6d, 0xe2, 0x5a, 0x42,
	0xb2, 0xea, 0xf9, 0x82, 0xe2, 0x87, 0x6d, 0x82, 0x4a, 0xb9, 0xfd, 0x5d, 0x03, 0x38, 0x95, 0xc8,
	0x6b, 0x78, 0xe5, 0xb3, 0x71, 0x40, 0xd9, 0x94, 0x4f, 0x86, 0x6c, 0x3a, 0x0a, 0xef, 0xc2, 0xe8,
	0x21, 0x74, 0xfe, 0x23, 0x57, 0xd0, 0x50, 0x0b, 0xc3, 0x7e, 0xc4, 0xa3, 0x71, 0x34, 0xe0, 0xdd,
	0x80, 0x4e, 0xe3, 0x49, 0xcc, 0xd9, 0xbd, 0xa3, 0x91, 0x26, 0x5c, 0xaa, 0x4d, 0x6c, 0xc0, 0x28,
	0xc7, 0x80, 0x4e, 0xc7, 0xac, 0x1f, 0xd0, 0x01, 0x73, 0xf4, 0x3f, 0xf5, 0x6f, 0xbb, 0x9c, 0x33,
	0x9c, 0x38, 0x46, 0xfb, 0x13, 0x58, 0xf2, 0x84, 0x09, 0x81, 0x5a, 0xcc, 0xbb, 0x7c, 0x14, 0x2b,
	0xee, 0xe7, 0x60, 0x97, 0x5c, 0x74, 0xe7, 0x68, 0x4a, 0xcb, 0x43, 0x17, 0xc3, 0x20, 0xec, 0x39,
	0x3a, 0x71, 0xe0, 0xff, 0x92, 0x63, 0x88, 0x11, 0x3a, 0x46, 0x9b, 0x43, 0x45, 0xec, 0x91, 0xbc,
	0x84, 0x73, 0x3a, 0xe8, 0xc6, 0xaa, 0x20, 0x81, 0x9a, 0xa4, 0x68, 0x14, 0xc6, 0xa3, 0x7b, 0x86,
	0x52, 0x55, 0x72, 0x43, 0x8c, 0xfc, 0x11, 0x65, 0x28, 0x55, 0x25, 0xd7, 0x9f, 0xdc, 0x62, 0xe0,
	0x3b, 0xc6, 0xdc, 0x12, 0xb7, 0xeb, 0xdd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x2c, 0x9f,
	0x88, 0xbe, 0x03, 0x00, 0x00,
}
